# fly.toml file generated for quaiantique on 2023-03-09T03:41:27+01:00

app = "quaiantique"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
  source="mydata"
  destination="/data"

[env]
  MYSQL_DATABASE = "some_db"
  MYSQL_USER = "non_root_user"

[build]
  builder = "heroku/buildpacks:20"
  

[experimental]
  cmd = [
    "--default-authentication-plugin", 
    "mysql_native_password", 
    "--datadir", 
    "/data/mysql"
  ]